#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLyVideoHocTap.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLVDHT")]
	public partial class DataQLBHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBinhLuan(BinhLuan instance);
    partial void UpdateBinhLuan(BinhLuan instance);
    partial void DeleteBinhLuan(BinhLuan instance);
    partial void InsertDKKH(DKKH instance);
    partial void UpdateDKKH(DKKH instance);
    partial void DeleteDKKH(DKKH instance);
    partial void InsertKhoaHoc(KhoaHoc instance);
    partial void UpdateKhoaHoc(KhoaHoc instance);
    partial void DeleteKhoaHoc(KhoaHoc instance);
    partial void InsertLichSuCoi(LichSuCoi instance);
    partial void UpdateLichSuCoi(LichSuCoi instance);
    partial void DeleteLichSuCoi(LichSuCoi instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertVideo(Video instance);
    partial void UpdateVideo(Video instance);
    partial void DeleteVideo(Video instance);
    #endregion
		
		public DataQLBHDataContext() : 
				base(global::Project_QuanLyVideoHocTap.Properties.Settings.Default.QLVDHTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLBHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLBHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLBHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQLBHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BinhLuan> BinhLuans
		{
			get
			{
				return this.GetTable<BinhLuan>();
			}
		}
		
		public System.Data.Linq.Table<DKKH> DKKHs
		{
			get
			{
				return this.GetTable<DKKH>();
			}
		}
		
		public System.Data.Linq.Table<KhoaHoc> KhoaHocs
		{
			get
			{
				return this.GetTable<KhoaHoc>();
			}
		}
		
		public System.Data.Linq.Table<LichSuCoi> LichSuCois
		{
			get
			{
				return this.GetTable<LichSuCoi>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<Video> Videos
		{
			get
			{
				return this.GetTable<Video>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimKh")]
		public ISingleResult<KhoaHoc> sp_TimKh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenKh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenKh);
			return ((ISingleResult<KhoaHoc>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TimVd")]
		public ISingleResult<Video> sp_TimVd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenVd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenVd);
			return ((ISingleResult<Video>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XemDsVd")]
		public ISingleResult<Video> sp_XemDsVd()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Video>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XemDsKh")]
		public ISingleResult<KhoaHoc> sp_XemDsKh()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<KhoaHoc>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XemDsVdTheoKh")]
		public ISingleResult<Video> sp_XemDsVdTheoKh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Video>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_DemVdTrongKh", IsComposable=true)]
		public System.Nullable<int> func_DemVdTrongKh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_DangNhap", IsComposable=true)]
		public System.Nullable<int> func_DangNhap([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string taiKhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string matKhau)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taiKhoan, matKhau).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XemTTTK")]
		public ISingleResult<TaiKhoan> sp_XemTTTK([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<TaiKhoan>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_KiemTraDKKH", IsComposable=true)]
		public System.Nullable<int> func_KiemTraDKKH([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idKh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTk)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idKh, idTk).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Themkh")]
		public ISingleResult<DKKH> sp_Themkh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idKh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idKh, idTk);
			return ((ISingleResult<DKKH>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XemDsKhCuaToi")]
		public ISingleResult<sp_XemDsKhCuaToiResult> sp_XemDsKhCuaToi([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sp_XemDsKhCuaToiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pc_HuyDKKH")]
		public int pc_HuyDKKH([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idKh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idKh, idTk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_DemKhoaHocDk", IsComposable=true)]
		public System.Nullable<int> func_DemKhoaHocDk([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XemVd")]
		public ISingleResult<sp_XemVdResult> sp_XemVd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVd, idTk);
			return ((ISingleResult<sp_XemVdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_DemTongLuotXem", IsComposable=true)]
		public System.Nullable<int> func_DemTongLuotXem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTk)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTk).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DoiMk")]
		public int sp_DoiMk([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tenDn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string matKhau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTk, tenDn, matKhau);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DsIdVDaXem")]
		public ISingleResult<sp_DsIdVDaXemResult> sp_DsIdVDaXem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<sp_DsIdVDaXemResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_VideoSaCoi", IsComposable=true)]
		public IQueryable<func_VideoSaCoiResult> func_VideoSaCoi([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return this.CreateMethodCallQuery<func_VideoSaCoiResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_LayTenKhCuaVd", IsComposable=true)]
		public string func_LayTenKhCuaVd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_LayBinhLuan")]
		public ISingleResult<sp_LayBinhLuanResult> sp_LayBinhLuan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVd);
			return ((ISingleResult<sp_LayBinhLuanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_BinhLuanVoVd")]
		public int sp_BinhLuanVoVd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string noiDung, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), noiDung, idVd, idTk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XoaKhoaHoc")]
		public int sp_XoaKhoaHoc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idKh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idKh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XoaVideo")]
		public int sp_XoaVideo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVd);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_KiemTraDaCoiVdChua")]
		public ISingleResult<sp_KiemTraDaCoiVdChuaResult> sp_KiemTraDaCoiVdChua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVd, idTk);
			return ((ISingleResult<sp_KiemTraDaCoiVdChuaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_KiemTraDaCoiVdChua", IsComposable=true)]
		public System.Nullable<int> func_KiemTraDaCoiVdChua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTk)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVd, idTk).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_XoaVideoKhoiKh")]
		public int sp_XoaVideoKhoiKh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVd);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TaoKhoaHoc")]
		public int sp_TaoKhoaHoc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ten", DbType="NVarChar(100)")] string ten)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ten);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TaoVd")]
		public int sp_TaoVd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string urlThumbails, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string urlVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idKh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenVd, urlThumbails, urlVd, idKh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_KtraKhTonTaiChua", IsComposable=true)]
		public System.Nullable<int> func_KtraKhTonTaiChua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenKh)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenKh).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_KtrVdTonTaiChua", IsComposable=true)]
		public System.Nullable<int> func_KtrVdTonTaiChua([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string urlThumbails, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string urlVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idKh)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenVd, urlThumbails, urlVd, idKh).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SuaVd")]
		public int sp_SuaVd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string urlThumbails, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string urlVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idKh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idVd, tenVd, urlThumbails, urlVd, idKh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SuaKh")]
		public int sp_SuaKh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idKh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string ten)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idKh, ten);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_KtraKhTonTaiId", IsComposable=true)]
		public System.Nullable<int> func_KtraKhTonTaiId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TaoVdNoIdKh")]
		public int sp_TaoVdNoIdKh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenVd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string urlThumbails, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string urlVd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenVd, urlThumbails, urlVd);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fuc_ThongKe", IsComposable=true)]
		public IQueryable<fuc_ThongKeResult> fuc_ThongKe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngayBd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngayKt)
		{
			return this.CreateMethodCallQuery<fuc_ThongKeResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngayBd, ngayKt);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.func_CheckUser", IsComposable=true)]
		public System.Nullable<int> func_CheckUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string ten)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ten).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TaoUser")]
		public int sp_TaoUser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string tenDn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string matKhau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenDn, matKhau);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BinhLuan")]
	public partial class BinhLuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idBl;
		
		private string _noiDung;
		
		private int _idVd;
		
		private int _idTk;
		
		private System.DateTime _ngayBl;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
		private EntityRef<Video> _Video;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBlChanging(int value);
    partial void OnidBlChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    partial void OnidVdChanging(int value);
    partial void OnidVdChanged();
    partial void OnidTkChanging(int value);
    partial void OnidTkChanged();
    partial void OnngayBlChanging(System.DateTime value);
    partial void OnngayBlChanged();
    #endregion
		
		public BinhLuan()
		{
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			this._Video = default(EntityRef<Video>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBl", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idBl
		{
			get
			{
				return this._idBl;
			}
			set
			{
				if ((this._idBl != value))
				{
					this.OnidBlChanging(value);
					this.SendPropertyChanging();
					this._idBl = value;
					this.SendPropertyChanged("idBl");
					this.OnidBlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVd", DbType="Int NOT NULL")]
		public int idVd
		{
			get
			{
				return this._idVd;
			}
			set
			{
				if ((this._idVd != value))
				{
					if (this._Video.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidVdChanging(value);
					this.SendPropertyChanging();
					this._idVd = value;
					this.SendPropertyChanged("idVd");
					this.OnidVdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTk", DbType="Int NOT NULL")]
		public int idTk
		{
			get
			{
				return this._idTk;
			}
			set
			{
				if ((this._idTk != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTkChanging(value);
					this.SendPropertyChanging();
					this._idTk = value;
					this.SendPropertyChanged("idTk");
					this.OnidTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBl", DbType="Date NOT NULL")]
		public System.DateTime ngayBl
		{
			get
			{
				return this._ngayBl;
			}
			set
			{
				if ((this._ngayBl != value))
				{
					this.OnngayBlChanging(value);
					this.SendPropertyChanging();
					this._ngayBl = value;
					this.SendPropertyChanged("ngayBl");
					this.OnngayBlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_BinhLuan", Storage="_TaiKhoan", ThisKey="idTk", OtherKey="idTk", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._idTk = value.idTk;
					}
					else
					{
						this._idTk = default(int);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Video_BinhLuan", Storage="_Video", ThisKey="idVd", OtherKey="idVd", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Video Video
		{
			get
			{
				return this._Video.Entity;
			}
			set
			{
				Video previousValue = this._Video.Entity;
				if (((previousValue != value) 
							|| (this._Video.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Video.Entity = null;
						previousValue.BinhLuans.Remove(this);
					}
					this._Video.Entity = value;
					if ((value != null))
					{
						value.BinhLuans.Add(this);
						this._idVd = value.idVd;
					}
					else
					{
						this._idVd = default(int);
					}
					this.SendPropertyChanged("Video");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DKKH")]
	public partial class DKKH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDk;
		
		private int _idKh;
		
		private int _idTk;
		
		private EntityRef<KhoaHoc> _KhoaHoc;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDkChanging(int value);
    partial void OnidDkChanged();
    partial void OnidKhChanging(int value);
    partial void OnidKhChanged();
    partial void OnidTkChanging(int value);
    partial void OnidTkChanged();
    #endregion
		
		public DKKH()
		{
			this._KhoaHoc = default(EntityRef<KhoaHoc>);
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDk", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDk
		{
			get
			{
				return this._idDk;
			}
			set
			{
				if ((this._idDk != value))
				{
					this.OnidDkChanging(value);
					this.SendPropertyChanging();
					this._idDk = value;
					this.SendPropertyChanged("idDk");
					this.OnidDkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKh", DbType="Int NOT NULL")]
		public int idKh
		{
			get
			{
				return this._idKh;
			}
			set
			{
				if ((this._idKh != value))
				{
					if (this._KhoaHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKhChanging(value);
					this.SendPropertyChanging();
					this._idKh = value;
					this.SendPropertyChanged("idKh");
					this.OnidKhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTk", DbType="Int NOT NULL")]
		public int idTk
		{
			get
			{
				return this._idTk;
			}
			set
			{
				if ((this._idTk != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTkChanging(value);
					this.SendPropertyChanging();
					this._idTk = value;
					this.SendPropertyChanged("idTk");
					this.OnidTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaHoc_DKKH", Storage="_KhoaHoc", ThisKey="idKh", OtherKey="idKh", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public KhoaHoc KhoaHoc
		{
			get
			{
				return this._KhoaHoc.Entity;
			}
			set
			{
				KhoaHoc previousValue = this._KhoaHoc.Entity;
				if (((previousValue != value) 
							|| (this._KhoaHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhoaHoc.Entity = null;
						previousValue.DKKHs.Remove(this);
					}
					this._KhoaHoc.Entity = value;
					if ((value != null))
					{
						value.DKKHs.Add(this);
						this._idKh = value.idKh;
					}
					else
					{
						this._idKh = default(int);
					}
					this.SendPropertyChanged("KhoaHoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_DKKH", Storage="_TaiKhoan", ThisKey="idTk", OtherKey="idTk", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.DKKHs.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.DKKHs.Add(this);
						this._idTk = value.idTk;
					}
					else
					{
						this._idTk = default(int);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhoaHoc")]
	public partial class KhoaHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idKh;
		
		private string _tenKh;
		
		private System.DateTime _ngayTao;
		
		private EntitySet<DKKH> _DKKHs;
		
		private EntitySet<Video> _Videos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidKhChanging(int value);
    partial void OnidKhChanged();
    partial void OntenKhChanging(string value);
    partial void OntenKhChanged();
    partial void OnngayTaoChanging(System.DateTime value);
    partial void OnngayTaoChanged();
    #endregion
		
		public KhoaHoc()
		{
			this._DKKHs = new EntitySet<DKKH>(new Action<DKKH>(this.attach_DKKHs), new Action<DKKH>(this.detach_DKKHs));
			this._Videos = new EntitySet<Video>(new Action<Video>(this.attach_Videos), new Action<Video>(this.detach_Videos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idKh
		{
			get
			{
				return this._idKh;
			}
			set
			{
				if ((this._idKh != value))
				{
					this.OnidKhChanging(value);
					this.SendPropertyChanging();
					this._idKh = value;
					this.SendPropertyChanged("idKh");
					this.OnidKhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKh", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenKh
		{
			get
			{
				return this._tenKh;
			}
			set
			{
				if ((this._tenKh != value))
				{
					this.OntenKhChanging(value);
					this.SendPropertyChanging();
					this._tenKh = value;
					this.SendPropertyChanged("tenKh");
					this.OntenKhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayTao", DbType="Date NOT NULL")]
		public System.DateTime ngayTao
		{
			get
			{
				return this._ngayTao;
			}
			set
			{
				if ((this._ngayTao != value))
				{
					this.OnngayTaoChanging(value);
					this.SendPropertyChanging();
					this._ngayTao = value;
					this.SendPropertyChanged("ngayTao");
					this.OnngayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaHoc_DKKH", Storage="_DKKHs", ThisKey="idKh", OtherKey="idKh")]
		public EntitySet<DKKH> DKKHs
		{
			get
			{
				return this._DKKHs;
			}
			set
			{
				this._DKKHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaHoc_Video", Storage="_Videos", ThisKey="idKh", OtherKey="idKh")]
		public EntitySet<Video> Videos
		{
			get
			{
				return this._Videos;
			}
			set
			{
				this._Videos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DKKHs(DKKH entity)
		{
			this.SendPropertyChanging();
			entity.KhoaHoc = this;
		}
		
		private void detach_DKKHs(DKKH entity)
		{
			this.SendPropertyChanging();
			entity.KhoaHoc = null;
		}
		
		private void attach_Videos(Video entity)
		{
			this.SendPropertyChanging();
			entity.KhoaHoc = this;
		}
		
		private void detach_Videos(Video entity)
		{
			this.SendPropertyChanging();
			entity.KhoaHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichSuCoi")]
	public partial class LichSuCoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idVd;
		
		private int _idTk;
		
		private System.DateTime _ngayCoi;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
		private EntityRef<Video> _Video;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidVdChanging(int value);
    partial void OnidVdChanged();
    partial void OnidTkChanging(int value);
    partial void OnidTkChanged();
    partial void OnngayCoiChanging(System.DateTime value);
    partial void OnngayCoiChanged();
    #endregion
		
		public LichSuCoi()
		{
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			this._Video = default(EntityRef<Video>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVd", DbType="Int NOT NULL")]
		public int idVd
		{
			get
			{
				return this._idVd;
			}
			set
			{
				if ((this._idVd != value))
				{
					if (this._Video.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidVdChanging(value);
					this.SendPropertyChanging();
					this._idVd = value;
					this.SendPropertyChanged("idVd");
					this.OnidVdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTk", DbType="Int NOT NULL")]
		public int idTk
		{
			get
			{
				return this._idTk;
			}
			set
			{
				if ((this._idTk != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTkChanging(value);
					this.SendPropertyChanging();
					this._idTk = value;
					this.SendPropertyChanged("idTk");
					this.OnidTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCoi", DbType="Date NOT NULL")]
		public System.DateTime ngayCoi
		{
			get
			{
				return this._ngayCoi;
			}
			set
			{
				if ((this._ngayCoi != value))
				{
					this.OnngayCoiChanging(value);
					this.SendPropertyChanging();
					this._ngayCoi = value;
					this.SendPropertyChanged("ngayCoi");
					this.OnngayCoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_LichSuCoi", Storage="_TaiKhoan", ThisKey="idTk", OtherKey="idTk", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.LichSuCois.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.LichSuCois.Add(this);
						this._idTk = value.idTk;
					}
					else
					{
						this._idTk = default(int);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Video_LichSuCoi", Storage="_Video", ThisKey="idVd", OtherKey="idVd", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Video Video
		{
			get
			{
				return this._Video.Entity;
			}
			set
			{
				Video previousValue = this._Video.Entity;
				if (((previousValue != value) 
							|| (this._Video.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Video.Entity = null;
						previousValue.LichSuCois.Remove(this);
					}
					this._Video.Entity = value;
					if ((value != null))
					{
						value.LichSuCois.Add(this);
						this._idVd = value.idVd;
					}
					else
					{
						this._idVd = default(int);
					}
					this.SendPropertyChanged("Video");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTk;
		
		private string _tenDn;
		
		private string _matKhau;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<DKKH> _DKKHs;
		
		private EntitySet<LichSuCoi> _LichSuCois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTkChanging(int value);
    partial void OnidTkChanged();
    partial void OntenDnChanging(string value);
    partial void OntenDnChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._DKKHs = new EntitySet<DKKH>(new Action<DKKH>(this.attach_DKKHs), new Action<DKKH>(this.detach_DKKHs));
			this._LichSuCois = new EntitySet<LichSuCoi>(new Action<LichSuCoi>(this.attach_LichSuCois), new Action<LichSuCoi>(this.detach_LichSuCois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTk", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTk
		{
			get
			{
				return this._idTk;
			}
			set
			{
				if ((this._idTk != value))
				{
					this.OnidTkChanging(value);
					this.SendPropertyChanging();
					this._idTk = value;
					this.SendPropertyChanged("idTk");
					this.OnidTkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDn", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string tenDn
		{
			get
			{
				return this._tenDn;
			}
			set
			{
				if ((this._tenDn != value))
				{
					this.OntenDnChanging(value);
					this.SendPropertyChanging();
					this._tenDn = value;
					this.SendPropertyChanged("tenDn");
					this.OntenDnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="VarChar(20)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_BinhLuan", Storage="_BinhLuans", ThisKey="idTk", OtherKey="idTk")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_DKKH", Storage="_DKKHs", ThisKey="idTk", OtherKey="idTk")]
		public EntitySet<DKKH> DKKHs
		{
			get
			{
				return this._DKKHs;
			}
			set
			{
				this._DKKHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_LichSuCoi", Storage="_LichSuCois", ThisKey="idTk", OtherKey="idTk")]
		public EntitySet<LichSuCoi> LichSuCois
		{
			get
			{
				return this._LichSuCois;
			}
			set
			{
				this._LichSuCois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
		
		private void attach_DKKHs(DKKH entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_DKKHs(DKKH entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
		
		private void attach_LichSuCois(LichSuCoi entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_LichSuCois(LichSuCoi entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Videos")]
	public partial class Video : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idVd;
		
		private string _tenVd;
		
		private string _urlThumbails;
		
		private string _urlVd;
		
		private System.Nullable<int> _luotXem;
		
		private System.Nullable<int> _idKh;
		
		private System.DateTime _ngayDang;
		
		private EntitySet<BinhLuan> _BinhLuans;
		
		private EntitySet<LichSuCoi> _LichSuCois;
		
		private EntityRef<KhoaHoc> _KhoaHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidVdChanging(int value);
    partial void OnidVdChanged();
    partial void OntenVdChanging(string value);
    partial void OntenVdChanged();
    partial void OnurlThumbailsChanging(string value);
    partial void OnurlThumbailsChanged();
    partial void OnurlVdChanging(string value);
    partial void OnurlVdChanged();
    partial void OnluotXemChanging(System.Nullable<int> value);
    partial void OnluotXemChanged();
    partial void OnidKhChanging(System.Nullable<int> value);
    partial void OnidKhChanged();
    partial void OnngayDangChanging(System.DateTime value);
    partial void OnngayDangChanged();
    #endregion
		
		public Video()
		{
			this._BinhLuans = new EntitySet<BinhLuan>(new Action<BinhLuan>(this.attach_BinhLuans), new Action<BinhLuan>(this.detach_BinhLuans));
			this._LichSuCois = new EntitySet<LichSuCoi>(new Action<LichSuCoi>(this.attach_LichSuCois), new Action<LichSuCoi>(this.detach_LichSuCois));
			this._KhoaHoc = default(EntityRef<KhoaHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idVd
		{
			get
			{
				return this._idVd;
			}
			set
			{
				if ((this._idVd != value))
				{
					this.OnidVdChanging(value);
					this.SendPropertyChanging();
					this._idVd = value;
					this.SendPropertyChanged("idVd");
					this.OnidVdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenVd", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenVd
		{
			get
			{
				return this._tenVd;
			}
			set
			{
				if ((this._tenVd != value))
				{
					this.OntenVdChanging(value);
					this.SendPropertyChanging();
					this._tenVd = value;
					this.SendPropertyChanged("tenVd");
					this.OntenVdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlThumbails", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string urlThumbails
		{
			get
			{
				return this._urlThumbails;
			}
			set
			{
				if ((this._urlThumbails != value))
				{
					this.OnurlThumbailsChanging(value);
					this.SendPropertyChanging();
					this._urlThumbails = value;
					this.SendPropertyChanged("urlThumbails");
					this.OnurlThumbailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlVd", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string urlVd
		{
			get
			{
				return this._urlVd;
			}
			set
			{
				if ((this._urlVd != value))
				{
					this.OnurlVdChanging(value);
					this.SendPropertyChanging();
					this._urlVd = value;
					this.SendPropertyChanged("urlVd");
					this.OnurlVdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luotXem", DbType="Int")]
		public System.Nullable<int> luotXem
		{
			get
			{
				return this._luotXem;
			}
			set
			{
				if ((this._luotXem != value))
				{
					this.OnluotXemChanging(value);
					this.SendPropertyChanging();
					this._luotXem = value;
					this.SendPropertyChanged("luotXem");
					this.OnluotXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKh", DbType="Int")]
		public System.Nullable<int> idKh
		{
			get
			{
				return this._idKh;
			}
			set
			{
				if ((this._idKh != value))
				{
					if (this._KhoaHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidKhChanging(value);
					this.SendPropertyChanging();
					this._idKh = value;
					this.SendPropertyChanged("idKh");
					this.OnidKhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDang", DbType="Date NOT NULL")]
		public System.DateTime ngayDang
		{
			get
			{
				return this._ngayDang;
			}
			set
			{
				if ((this._ngayDang != value))
				{
					this.OnngayDangChanging(value);
					this.SendPropertyChanging();
					this._ngayDang = value;
					this.SendPropertyChanged("ngayDang");
					this.OnngayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Video_BinhLuan", Storage="_BinhLuans", ThisKey="idVd", OtherKey="idVd")]
		public EntitySet<BinhLuan> BinhLuans
		{
			get
			{
				return this._BinhLuans;
			}
			set
			{
				this._BinhLuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Video_LichSuCoi", Storage="_LichSuCois", ThisKey="idVd", OtherKey="idVd")]
		public EntitySet<LichSuCoi> LichSuCois
		{
			get
			{
				return this._LichSuCois;
			}
			set
			{
				this._LichSuCois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhoaHoc_Video", Storage="_KhoaHoc", ThisKey="idKh", OtherKey="idKh", IsForeignKey=true, DeleteRule="CASCADE")]
		public KhoaHoc KhoaHoc
		{
			get
			{
				return this._KhoaHoc.Entity;
			}
			set
			{
				KhoaHoc previousValue = this._KhoaHoc.Entity;
				if (((previousValue != value) 
							|| (this._KhoaHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhoaHoc.Entity = null;
						previousValue.Videos.Remove(this);
					}
					this._KhoaHoc.Entity = value;
					if ((value != null))
					{
						value.Videos.Add(this);
						this._idKh = value.idKh;
					}
					else
					{
						this._idKh = default(Nullable<int>);
					}
					this.SendPropertyChanged("KhoaHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Video = this;
		}
		
		private void detach_BinhLuans(BinhLuan entity)
		{
			this.SendPropertyChanging();
			entity.Video = null;
		}
		
		private void attach_LichSuCois(LichSuCoi entity)
		{
			this.SendPropertyChanging();
			entity.Video = this;
		}
		
		private void detach_LichSuCois(LichSuCoi entity)
		{
			this.SendPropertyChanging();
			entity.Video = null;
		}
	}
	
	public partial class sp_XemDsKhCuaToiResult
	{
		
		private int _idKh;
		
		private string _tenKh;
		
		public sp_XemDsKhCuaToiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idKh", DbType="Int NOT NULL")]
		public int idKh
		{
			get
			{
				return this._idKh;
			}
			set
			{
				if ((this._idKh != value))
				{
					this._idKh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKh", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenKh
		{
			get
			{
				return this._tenKh;
			}
			set
			{
				if ((this._tenKh != value))
				{
					this._tenKh = value;
				}
			}
		}
	}
	
	public partial class sp_XemVdResult
	{
		
		private System.Nullable<int> _Column1;
		
		public sp_XemVdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class sp_DsIdVDaXemResult
	{
		
		private int _idVd;
		
		public sp_DsIdVDaXemResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVd", DbType="Int NOT NULL")]
		public int idVd
		{
			get
			{
				return this._idVd;
			}
			set
			{
				if ((this._idVd != value))
				{
					this._idVd = value;
				}
			}
		}
	}
	
	public partial class func_VideoSaCoiResult
	{
		
		private int _idVd;
		
		public func_VideoSaCoiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVd", DbType="Int NOT NULL")]
		public int idVd
		{
			get
			{
				return this._idVd;
			}
			set
			{
				if ((this._idVd != value))
				{
					this._idVd = value;
				}
			}
		}
	}
	
	public partial class sp_LayBinhLuanResult
	{
		
		private int _id;
		
		private string _noiDung;
		
		private System.DateTime _ngay;
		
		public sp_LayBinhLuanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NVarChar(232)")]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this._noiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay", DbType="Date NOT NULL")]
		public System.DateTime ngay
		{
			get
			{
				return this._ngay;
			}
			set
			{
				if ((this._ngay != value))
				{
					this._ngay = value;
				}
			}
		}
	}
	
	public partial class sp_KiemTraDaCoiVdChuaResult
	{
		
		private System.Nullable<int> _sl;
		
		public sp_KiemTraDaCoiVdChuaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl", DbType="Int")]
		public System.Nullable<int> sl
		{
			get
			{
				return this._sl;
			}
			set
			{
				if ((this._sl != value))
				{
					this._sl = value;
				}
			}
		}
	}
	
	public partial class fuc_ThongKeResult
	{
		
		private System.Nullable<int> _tongView;
		
		private System.Nullable<int> _tongBl;
		
		private string _tenVdXemNn;
		
		private string _tenVdBlNn;
		
		private string _tenKhXemNn;
		
		private string _tenTkXemNn;
		
		private string _tenTkBlNn;
		
		public fuc_ThongKeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongView", DbType="Int")]
		public System.Nullable<int> tongView
		{
			get
			{
				return this._tongView;
			}
			set
			{
				if ((this._tongView != value))
				{
					this._tongView = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongBl", DbType="Int")]
		public System.Nullable<int> tongBl
		{
			get
			{
				return this._tongBl;
			}
			set
			{
				if ((this._tongBl != value))
				{
					this._tongBl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenVdXemNn", DbType="NVarChar(100)")]
		public string tenVdXemNn
		{
			get
			{
				return this._tenVdXemNn;
			}
			set
			{
				if ((this._tenVdXemNn != value))
				{
					this._tenVdXemNn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenVdBlNn", DbType="NVarChar(100)")]
		public string tenVdBlNn
		{
			get
			{
				return this._tenVdBlNn;
			}
			set
			{
				if ((this._tenVdBlNn != value))
				{
					this._tenVdBlNn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhXemNn", DbType="NVarChar(100)")]
		public string tenKhXemNn
		{
			get
			{
				return this._tenKhXemNn;
			}
			set
			{
				if ((this._tenKhXemNn != value))
				{
					this._tenKhXemNn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTkXemNn", DbType="NVarChar(30)")]
		public string tenTkXemNn
		{
			get
			{
				return this._tenTkXemNn;
			}
			set
			{
				if ((this._tenTkXemNn != value))
				{
					this._tenTkXemNn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTkBlNn", DbType="NVarChar(30)")]
		public string tenTkBlNn
		{
			get
			{
				return this._tenTkBlNn;
			}
			set
			{
				if ((this._tenTkBlNn != value))
				{
					this._tenTkBlNn = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
